# KRM blueprint metadata.
# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: terraform-google-app-engine
  source:
    sourceType: git
    git:
      repo: https://github.com/GoogleCloudPlatform/terraform-google-app-engine.git
      # A pseudo version for this generated example
      ref: main
  version: 1.0.0
  actuationTool:
    type: Terraform
    version: ">= 1.3"
    flavor: HCL
  info:
    title: Google Cloud App Engine Module
    tagline: A comprehensive Terraform module for deploying and managing Google Cloud App Engine applications, services, and versions.
    description: |-
      This Terraform module simplifies the deployment of applications on Google Cloud App Engine.
      It supports creating the App Engine application itself, deploying multiple services with multiple versions, and configuring traffic splitting.
      It handles both Standard and Flexible environments, with detailed configuration options for scaling, health checks, networking, and environment variables.
    deployment_duration_in_minutes: 10
    cost_estimate:
      description: "Cost varies based on instance classes, scaling settings, and traffic. See the official App Engine pricing page for details."
      url: "https://cloud.google.com/appengine/pricing"
    architecture:
      diagram_url: "" # Placeholder for architecture diagram URL
      description: "This module creates an App Engine Application within a GCP project. It can deploy one or more services, such as a 'default' web frontend and a 'backend-api'. Each service can have multiple versions deployed simultaneously, with traffic split between them. Versions can be configured for either the Standard or Flexible environment."
    documentation:
    - title: "Module README"
      url: "" # Placeholder for README URL
    - title: "App Engine Documentation"
      url: "https://cloud.google.com/appengine/docs"
    icon: "static/assets/gcp_icons/app-engine.svg"
spec:
  requirements:
    services:
      - appengine.googleapis.com
      - cloudbuild.googleapis.com
      - storage.googleapis.com
      - iam.googleapis.com
    roles:
      - role: roles/appengine.admin
        level: project
      - role: roles/storage.objectAdmin
        level: project
      - role: roles/cloudbuild.builds.editor
        level: project
      - role: roles/iam.serviceAccountUser
        level: project
  interfaces:
    variables:
      - name: project_id
        description: "The ID of the project in which to create the App Engine application. If not specified, the provider's project will be used."
        varType: string
        defaultValue: null
        required: false
      - name: location_id
        description: "The location to serve the app from, e.g. `us-central`. Defaults to `us-central`."
        varType: string
        defaultValue: "us-central"
        required: false
      - name: create_app
        description: "A boolean to control the creation of the `google_app_engine_application` resource. Set to `false` if you are only deploying services to an existing application."
        varType: bool
        defaultValue: true
        required: false
      - name: auth_domain
        description: "The domain to authenticate users with when using App Engine's User API. A G Suite domain is required if IAP is enabled."
        varType: string
        defaultValue: null
        required: false
      - name: serving_status
        description: "The serving status of the application. Can be `SERVING` or `USER_DISABLED`."
        varType: string
        defaultValue: "SERVING"
        required: false
      - name: database_type
        description: "The type of the database to use. Can be `CLOUD_FIRESTORE` or `CLOUD_DATASTORE_COMPATIBILITY`. If not specified, it will be chosen based on the project's history."
        varType: string
        defaultValue: null
        required: false
      - name: feature_settings
        description: "A map of feature settings to configure on the application."
        varType: object
        defaultValue:
          split_health_checks: true
        required: false
      - name: iap
        description: "Identity-Aware Proxy (IAP) configuration for the App Engine application. If this is block is not provided, IAP will be disabled."
        varType: object
        defaultValue: null
        required: false
        sensitive: true
      - name: services
        description: "A map of App Engine services to deploy. The map key is the service name (e.g., 'default', 'api')."
        varType: map(object)
        defaultValue: {}
        required: true # Even with a default, this complex input is the core of the module.
    variableGroups:
      - name: "Application Settings"
        description: "Core settings for the App Engine application."
        variables:
          - project_id
          - location_id
          - create_app
          - serving_status
      - name: "Application Configuration"
        description: "Optional configurations for the App Engine application."
        variables:
          - auth_domain
          - database_type
          - feature_settings
          - iap
      - name: "Services & Versions"
        description: "The detailed configuration for all services and versions to be deployed."
        variables:
          - services
    outputs:
      - name: app_id
        description: "The globally unique identifier for the App Engine application."
      - name: app_url
        description: "The default URL to access the App Engine application."
      - name: app_gcr_domain
        description: "The GCR domain used for storing instance images."
      - name: standard_versions
        description: "A map of the deployed App Engine standard versions."
      - name: flexible_versions
        description: "A map of the deployed App Engine flexible versions."
      - name: service_urls
        description: "A map of service names to their default URLs. This is only populated if `create_app` is true."
